{% set version = "2.3.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-snftool
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/SNFtool_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/SNFtool/SNFtool_{{ version }}.tar.gz
  sha256: 982fe7c57f52c0c272b8cb5863dc5d50623b368e24ff6e27fc8b17acc0101f16

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-exposition
    - r-alluvial
  run:
    - r-base
    - r-exposition
    - r-alluvial

test:
  commands:
    - $R -e "library('SNFtool')"           # [not win]
    - "\"%R%\" -e \"library('SNFtool')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=SNFtool
  license: GPL-2.0-or-later
  summary: Similarity Network Fusion takes multiple views of a network and fuses them together to construct an overall status matrix. The input to our algorithm can be feature vectors, pairwise distances, or pairwise similarities. The learned status matrix can then be used for retrieval, clustering, and classification.
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: SNFtool
# Type: Package
# Title: Similarity Network Fusion
# Version: 2.3.0
# Date: 2018-04-24
# Author: Bo Wang, Aziz Mezlini, Feyyaz Demir, Marc Fiume, Zhuowen Tu, Michael Brudno, Benjamin Haibe-Kains, Anna Goldenberg
# Maintainer: Daniel Cole <goldenberglab@gmail.com>
# Imports: heatmap.plus, ExPosition, alluvial
# Description: Similarity Network Fusion takes multiple views of a network and fuses them together to construct an overall status matrix. The input to our algorithm can be feature vectors, pairwise distances, or pairwise similarities. The learned status matrix can then be used for retrieval, clustering, and classification.
# License: GPL
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2018-04-24 16:23:07 UTC
# Packaged: 2018-04-24 15:59:51 UTC; danielcole
