travis:
  secure:
    BINSTAR_TOKEN: vJrYwzAWyRShaTx3/XMhLeniWsGaEWe5ciMEb6NcIkxD6RKTSGSefHnrcipkmYy5gkyCvcIxZ1rihMG9I3sNytb6nL3SWjbf1i2Dr8TZGJd7fWCOmizx89S73cCFPRXQnWMhNxJrL0E5IpgtoZSf5B8H2wQbJjYzEQX1Tgoc0A5tgTOPFke46laxVmHqg7LJyqziN88WZDsC0c3LInv4JqXXwlXCu/wF4HDz7u9+UZ3dqlvga94qzsHCQJBu6kZedXdX/NFcZa1ww1q/ixS3WTOZYsLXR+4QMahYgQ/KbkLXoiReWSBy1LYzLAA6Yc9YWKQVqGhM+4Nugbw672IwSGmunZLXVjR+MNxxajLN+XPNyaUXHHcOoruY3Q5EMo/hOeAiNOl131CljQA2hUPbyIZ6BjmD7VCO2nOx6lbDpnzAxOlJ0jus9O3XZNunGPi45Io8rWLiRcog41G33UAN5xhUo+DRi6fftwah4nU/r8WlSv8zkRuqZuh3LJDIEWW3IjQjj5Joc/iGUrcTtyBtI7erjUPPA7uH1Ih8th+NixzKPqkBtu6Tid2av9NaSprNh2ORWqu5mGQuuRc26ZNqrwp4UxoV7TjG0/9edUgZcNLD6enSGMhl16nTpdkejRYiGqsA22Guee7/spCn41tHWRsCIBtXlCXk+Hgf+Morndk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
