appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: XCq81hhzep0WOx5HvZUhkb5byI1ijS2BrVoGE//mj3cSKo1NWanvrTih91Ei5Q7gdzcm63N9xEkdMM6GjBz4sUcQOljhsSoovoWB7KDadBI5m37f23kZjLB4MuaLMV1kXbDP+Q+4lYP0lMZWfxi3ncQM4utEP2VlOYY18AuaNdFoQdlcPcuFn558hryznmxKjTHEUKjXMnMw82Iu9kf3fmysSxPeoRXTwZ9iNCS56VVA6Xgkk9LbUT/NqhncXf69hsQEuRJxjX7TyyvTBlZ8HCVzddRYtfoGenLCmljWmtBE6Eozbrec9nt08INOCaQ7NdQE67qQD8Chvtwzq+Nk7Fp6ja2+DntlsW4555nsgXA8QSRthAcwOieI3bbWNg/SE1CLzWjRL6o6Sc9YK7IhTSt+zk7i82rve4Y4KDsK9RPQvM54trU614qVgnxkr2HAv5GTeFufvZ6vdtkSkO+19rxRLlsqMzSZmBwTx3x7Z3GDP3NTsLbo9LBJNNGGfgr1MHv2uXVkW5BpTAWTzI0Nx3PblL8Ssm5WnsFtvg+MjJOicxqy0ahMhmVg2Y086+l9dsWVVsFEdV0C43gcz/mcc/Do2RkHB4gRRluFUt/RVnboU29rAnpjoSFxZsDIiNM1DDu3X47ciUC0aEErmYGIYCzfUPz1jz6bv9+xGVDLizA=
conda_forge_output_validation: false
