travis:
  secure:
    BINSTAR_TOKEN: E20JMle4MDqmntisBZmr/eZyfFZhIzEO3S0yC/JUVE/Xo+aEFxhpvMbQXiqPpUJ1Z50DN4X9cUlBVVbiPPUjxMNhvOAkfvyV+E00/RylbP5a/9VB6iofmG3WmJHdDPsZSN6mGHmYP+6KRGraMbKpdtoXjO/QV1MtqO1HJ3A2Q1U19zjPegzLqYb2949YN1XE2M0zVV4N9nJ+vLDXGYe1bxJFkOzj72yvd6mVuTEJC5KE1SdU7vx5e1g+cmXJSAVYWVTrEjSof+cv2PSDAoKqYnySwE00Ye10if1yFrRyvRyEPndYHKOSF2wj5dpCQ5IpeuHS3YTjd17c4pph+q8LE4w52N5QA0CPS2s6HwfGGPErHFx8zv8FtBPsakRPNGbL8tNkTZpPsf21F9O7dDMk6FKrejKwi4i/tx5L7SveNpoHrX6vszBaXA1QFE/Eo8GUHGfPNJP+xtwdcVcbi69MbeTGf8+AIs99ZNbBIkoZfNpIW/M0GDRAwEAfqWYiLpiTMkXkSscIzTBwgQoFukcD+K/+61/HNAwUJM1xg9jfFfW0q3oKR4A18SF4kATBeL7B0D1AfBZle9LrHhJC5gKQbd0L9XwG60bcsc1mcz+RsICMV7LJ63YPE+TVgNJSgcSnpFXRTSu0SkZbLMwXqxfrI2mirO23TtKdIkWoW6pas80=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
